In [40]:
np.array(prediction)
idx_max = prediction.argmax()
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

rock


In [2]:


import numpy as np
my_list = [[0.1,0.8,0.05,0.05]]
max_val = max(my_list[0])
idx_max = my_list[0].index(max_val)
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

paper


In [21]:
prediction = [[0.1,0.2,0.9,0.05]]
max_val = max(prediction[0])
print(max_val)
idx_max = prediction[0].index(max_val)
print(idx_max)
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

0.9
2
scissors


In [16]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()

    seconds = 3 #set how many seconds to run the camera 
    computer_wins = 0
    user_wins = 0

    def __init__(self,rounds):
        self.rounds = 0 

    def get_prediction(self, rounds):        
        
        
        while self.rounds <= 3:
            model = load_model('keras_model.h5')
            cap = cv2.VideoCapture(0)
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            ret, frame = cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            data[0] = normalized_image
            cv2.imshow('frame', frame)
            prediction = model.predict(data)
            print(prediction) #test to see if the values are changing - REMOVE
    
            self.rounds = self.rounds + 1

            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                if self.rounds <= 3:
                    print('passing')
                    pass 
                else: 
                    break

            self.stop_camera(cap)#call the method to stop the camera
            self.get_user_choice(prediction)#call the convert the array to a choice
        
        else: 
            print('hit the last else') 
                

        
    def stop_camera(self, cap):
        print('1. stopped camera') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            CvRps.computer_wins += 1
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
            CvRps.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
            CvRps.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
            CvRps.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps(3)
    game.get_prediction(3)
    print('game end')
    cv2.VideoCapture(0).release()# After the loop release the cap object
    cv2.destroyAllWindows()# Destroy all the windows


play_rps()

1/1 [==============================] - 1s 1s/step
[[9.9996674e-01 3.1360076e-05 7.0703003e-08 1.7979771e-06]]
passing
1. stopped camera
[[9.9996674e-01 3.1360076e-05 7.0703003e-08 1.7979771e-06]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 1s/step
[[9.9944836e-01 5.5166020e-04 1.7203015e-10 2.7640686e-08]]
passing
1. stopped camera
[[9.9944836e-01 5.5166020e-04 1.7203015e-10 2.7640686e-08]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 1s/step
[[9.9997950e-01 1.9902533e-05 4.1473690e-08 6.3193073e-07]]
passing
1. stopped camera
[[9.9997950e-01 1.9902533e-05 4.1473690e-08 6.3193073e-07]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 917ms/step
[[9.9998534e-01 1.4193496e-05 1.5602939e-08 4.8147530e-07]]
game end


In [12]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()
    seconds = 7 #set how many seconds to run the camera 


    def __init__(self,rounds):
        self.rounds = 1
        self.computer_wins = 0
        self.user_wins = 0


    def get_prediction(self, rounds):        
        
        
        while self.user_wins < 4 and self.computer_wins < 4:
        

            if self.user_wins ==3 or self.computer_wins == 3:
                print(f" GAME ENDING:.... user score: {self.user_wins} ||| Computer score: {self.computer_wins}")
                break
            else: 
                print()
                print(f'----------Round: {self.rounds}-------------')
                self.rounds = self.rounds +1

                
                
                
                print(f"user score: {self.user_wins} ||| Computer score: {self.computer_wins}")
                model = load_model('keras_model2.h5')
                cap = cv2.VideoCapture(0)
                data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
                ret, frame = cap.read()
                resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
                image_np = np.array(resized_frame)
                normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
                data[0] = normalized_image
                cv2.imshow('frame', frame)
                print('Ok the camera is now on. Show me your choice')
                prediction = model.predict(data)

                print(f'the array from the prediction is: {prediction}') #test to see if the values are changing - REMOVE
                current_time = time.time()
                elapsed_time = current_time - CvRps.start_time
                if elapsed_time > CvRps.seconds:
                    self.stop_camera(cap)#call the method to stop the camera
                    self.get_user_choice(prediction)#call the convert the array to a choice
        
        else: 
            print('hit the last else') 
                

        
    def stop_camera(self, cap):
        print('...camera now stopping') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        print('...camera stopped') #just a test - REMOVE 
        pass   

    def get_user_choice(self, prediction):
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'...You chose {user_camera_choice}')
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f'...The computer chose {computer_choice}')
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        print(f"...You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        print(f'...checking result:')
        stars = '**********'
        if computer_choice == user_choice:
            print(f"{stars} It's a draw! {stars}")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            self.computer_wins += 1
            print(f'{stars} You lost {stars}')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print(f'{stars} You lost {stars}')
            self.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print(f'{stars} You lost {stars}')
            self.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps(3)
    game.get_prediction(3)
    print('game end')
    print()
    cv2.VideoCapture(0).release()# After the loop release the cap object
    cv2.destroyAllWindows()# Destroy all the windows


play_rps()


----------Round: 1-------------
user score: 0 ||| Computer score: 0
Ok the camera is now on. Show me your choice
1/1 [==============================] - 1s 1s/step
the array from the prediction is: [[0.05356555 0.02043165 0.88671833 0.03928454]]

----------Round: 2-------------
user score: 0 ||| Computer score: 0
Ok the camera is now on. Show me your choice
1/1 [==============================] - 1s 1s/step
the array from the prediction is: [[0.34405234 0.41415146 0.20065556 0.04114057]]

----------Round: 3-------------
user score: 0 ||| Computer score: 0
Ok the camera is now on. Show me your choice
1/1 [==============================] - 1s 1s/step
the array from the prediction is: [[0.6900617  0.0875589  0.19633086 0.02604858]]
...camera now stopping
...camera stopped
...You chose rock
...The computer chose paper
...You picked: rock. The computer picked paper
...checking result:
********** You lost **********

----------Round: 4-------------
user score: 0 ||| Computer score: 1
Ok the c

KeyboardInterrupt: 

In [20]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()
    seconds = 3 #set how many seconds to run the camera 


    def __init__(self,rounds):
        self.rounds = 1
        self.computer_wins = 0
        self.user_wins = 0

    def get_prediction(self, rounds):        
        
        
        # while self.user_wins < 4 and self.computer_wins < 4:
        while True:

            if self.user_wins ==3 or self.computer_wins == 3:
                print(f" GAME ENDING:.... user score: {self.user_wins} ||| Computer score: {self.computer_wins}")
                break
            else: 
                print(f'----------Round: {self.rounds}-------------')
                self.rounds = self.rounds +1
                pass 
            
            print(f"user score: {self.user_wins} ||| Computer score: {self.computer_wins}")
            model = load_model('keras_model.h5')
            cap = cv2.VideoCapture(0)
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            ret, frame = cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            data[0] = normalized_image
            cv2.imshow('frame', frame)
            print('Ok the camera is now on. Show me your choice')
            prediction = model.predict(data)

            print(prediction) #test to see if the values are changing - REMOVE

            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                self.stop_camera(cap)#call the method to stop the camera
                self.get_user_choice(prediction)#call the convert the array to a choice
        
        else: 
            print('hit the last else') 
                

        
    def stop_camera(self, cap):
        print('...camera now stopping') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        print('...camera stopped') #just a test - REMOVE 
        pass   

    def get_user_choice(self, prediction):
        np.array(prediction) #convert to array
        # idx_max = prediction.argmax() #find the max value
        idx_max = np.argmax(prediction[0])
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'...You chose {user_camera_choice}')
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f'...The computer chose {computer_choice}')
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        print(f"...You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        print(f'...checking result:')
        stars = '**********'
        if computer_choice == user_choice:
            print(f"{stars} It's a draw! {stars}")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            self.computer_wins += 1
            print(f'{stars} You lost {stars}')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print(f'{stars} You lost {stars}')
            self.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print(f'{stars} You won {stars} ')
            self.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print(f'{stars} You lost {stars}')
            self.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps(3)
    game.get_prediction(3)
    print('game end')
    print()
    cv2.VideoCapture(0).release()# After the loop release the cap object
    cv2.destroyAllWindows()# Destroy all the windows


play_rps()

----------Round: 1-------------
user score: 0 ||| Computer score: 0
Ok the camera is now on. Show me your choice
1/1 [==============================] - 1s 938ms/step
[[5.0708491e-07 9.9670249e-01 3.2966612e-03 4.0671151e-07]]
...camera now stopping
...camera stopped
...You chose paper
...The computer chose paper
...You picked: paper. The computer picked paper
...checking result:
********** It's a draw! **********
----------Round: 2-------------
user score: 0 ||| Computer score: 0
Ok the camera is now on. Show me your choice
1/1 [==============================] - 2s 2s/step
[[5.6689066e-07 9.9382520e-01 6.1736139e-03 6.2088452e-07]]
...camera now stopping
...camera stopped
...You chose paper
...The computer chose scissors
...You picked: paper. The computer picked scissors
...checking result:
********** You lost **********
----------Round: 3-------------
user score: 0 ||| Computer score: 1
Ok the camera is now on. Show me your choice
1/1 [==============================] - 1s 1s/step
[[6.