In [ ]:
# python -m venv rps_env
# source rps_env/bin/activate
# Me to Everyone (8:17 p.m.)
# Pip install —upgrade pip
code . to open the folder in the hting

In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2022-08-15 20:30:26.044351: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


1/1 [==============================] - 5s 5s/step


2022-08-15 20:30:41.551 Python[54609:4010639] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)


[[3.5898068e-03 7.0152844e-08 9.9628180e-01 1.2834559e-04]]
1/1 [==============================] - 0s 126ms/step
[[2.6787033e-03 2.2293165e-09 9.9635881e-01 9.6248143e-04]]
1/1 [==============================] - 0s 137ms/step
[[1.9854784e-02 2.2717089e-08 9.7470665e-01 5.4385071e-03]]
1/1 [==============================] - 0s 113ms/step
[[1.4453413e-03 1.4165964e-10 9.9827850e-01 2.7624139e-04]]
1/1 [==============================] - 0s 105ms/step
[[5.5524078e-04 1.0045732e-10 9.9909234e-01 3.5247824e-04]]
1/1 [==============================] - 0s 117ms/step
[[2.1757490e-03 3.7127128e-09 9.9076158e-01 7.0626363e-03]]
1/1 [==============================] - 0s 113ms/step
[[5.4745931e-05 6.5507577e-10 9.9977547e-01 1.6979720e-04]]
1/1 [==============================] - 0s 82ms/step
[[2.3521518e-04 3.9984262e-11 9.9958450e-01 1.8028193e-04]]
1/1 [==============================] - 0s 105ms/step
[[4.2565790e-04 1.4801466e-10 9.9837154e-01 1.2027983e-03]]
1/1 [==============================] 

KeyboardInterrupt: 