In [ ]:
# python -m venv rps_env
# source myenv/bin/activate
# Me to Everyone (8:17 p.m.)
# Pip install —upgrade pip
code . to open the folder in the hting

In [40]:
np.array(prediction)
idx_max = prediction.argmax()
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

rock


In [2]:


import numpy as np
my_list = [[0.1,0.8,0.05,0.05]]
max_val = max(my_list[0])
idx_max = my_list[0].index(max_val)
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

paper


In [21]:
prediction = [[0.1,0.2,0.9,0.05]]
max_val = max(prediction[0])
print(max_val)
idx_max = prediction[0].index(max_val)
print(idx_max)
choices = ["rock", "paper", "scissors", "nothing"]
print(choices[idx_max])

0.9
2
scissors


In [24]:
prediction = np.array([[0.9,0.2,0.1,0.05]])
prediction.argmax()

0

In [51]:
def choi():
    choice_list = ['rock', 'paper', 'scissors']
    choice_list1 = choice_list.append('nothing')
    return choice_list1
choi()

In [15]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    model = load_model('keras_model.h5')
    cap = cv2.VideoCapture(0)
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    start_time = time.time()
    seconds = 3

    def __init__(self):
        pass

    def get_prediction(self):        
        
        while True:
            ret, frame = CvRps.cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            CvRps.data[0] = normalized_image
            cv2.imshow('frame', frame)
            prediction = CvRps.model.predict(CvRps.data)
            # print(prediction) test to see if the values are changing - REMOVE
            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                break
        
        self.stop_camera()#call the method to stop the camera
        self.get_user_choice(prediction)#call the convert the array to a choice
                

        
    def stop_camera(self):
        print('1. stopped camera') #just a test - REMOVE 
        CvRps.cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps()
    game.get_prediction()
play_rps()

1/1 [==============================] - 0s 46ms/step
1. stopped camera
[[4.5376728e-05 9.9995315e-01 1.4347522e-06 2.4874132e-13]]
2. cv_choice var prints: paper
3. You picked: paper. The computer picked scissors
You lost


In [24]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()

    seconds = 3 #set how many seconds to run the camera 
    computer_wins = 0
    user_wins = 0

    def __init__(self):
        pass

    def get_prediction(self):        
        
        if CvRps.computer_wins or CvRps.user_wins < 3:
            while True:
                model = load_model('keras_model.h5')
                cap = cv2.VideoCapture(0)
                data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
                ret, frame = cap.read()
                resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
                image_np = np.array(resized_frame)
                normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
                data[0] = normalized_image
                cv2.imshow('frame', frame)
                prediction = model.predict(data)
                # print(prediction) test to see if the values are changing - REMOVE
                current_time = time.time()
                elapsed_time = current_time - CvRps.start_time
                if elapsed_time > CvRps.seconds:
                    break
            
            self.stop_camera(cap)#call the method to stop the camera
            self.get_user_choice(prediction)#call the convert the array to a choice
        elif CvRps.computer_wins == 3:
            print('Comupter wins')
        else:
            print('User wins the game')
                

        
    def stop_camera(self,cap):
        print('1. stopped camera') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            CvRps.computer_wins += 1
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
            CvRps.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
            CvRps.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
            CvRps.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps()
    game.get_prediction()


play_rps()

1/1 [==============================] - 1s 968ms/step
1. stopped camera
[[2.3885716e-09 9.9426693e-01 5.7331054e-03 4.1485808e-16]]
2. cv_choice var prints: paper
3. You picked: paper. The computer picked scissors
You lost


In [ ]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    model = load_model('keras_model.h5')
    cap = cv2.VideoCapture(0)
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    start_time = time.time()
    seconds = 3 #set how many seconds to run the camera 

    def __init__(self):
        pass

    def get_prediction(self):        
        
        while True:
            
            ret, frame = CvRps.cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            CvRps.data[0] = normalized_image
            cv2.imshow('frame', frame)
            prediction = CvRps.model.predict(CvRps.data)
            # print(prediction) test to see if the values are changing - REMOVE
            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                break
        
        self.stop_camera()#call the method to stop the camera
        self.get_user_choice(prediction)#call the convert the array to a choice
                

        
    def stop_camera(self):
        print('1. stopped camera') #just a test - REMOVE 
        CvRps.cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps()
    game.get_prediction()
# play_rps()

In [2]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time


class CvRps:
    
    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()
    seconds = 3 #set how many seconds to run the camera 
    user_wins = 0
    computer_wins = 0 
    rounds = 0
    def __init__(self):
        pass

    # def count_wins():
    #     while CvRps.computer_wins and CvRps.user_wins < 3:
    #         CvRps.get_prediction()
    #     else:
    #         if CvRps.user_wins == 3:
    #             print('user wins')
    #         else:
    #             print('computer wins')

    
    def get_prediction(self):        
        
        while CvRps.rounds < 3:
            CvRps.rounds = CvRps.rounds + 1
            model = load_model('keras_model.h5')
            cap = cv2.VideoCapture(0)
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            ret, frame = cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            data[0] = normalized_image
            cv2.imshow('frame', frame)
            prediction = model.predict(data)
            # print(prediction) test to see if the values are changing - REMOVE
            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                break
        
        self.stop_camera(cap)#call the method to stop the camera
        self.get_user_choice(prediction)#call the convert the array to a choice
                

        
    def stop_camera(self, cap):
        print('1. stopped camera') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            CvRps.computer_wins = CvRps.computer_wins + 1
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
            CvRps.computer_wins = CvRps.computer_wins + 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
            CvRps.computer_wins = CvRps.computer_wins + 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
            CvRps.computer_wins = CvRps.computer_wins + 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
            CvRps.computer_wins = CvRps.computer_wins + 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
            CvRps.computer_wins = CvRps.computer_wins + 1
        else:
            print('No Result: Seems to be an error somewhere')
        
def play_rps():
    game = CvRps()
    # while True:
    #     print(f'user wins are: {game.user_wins} |||| computer wins are: {game.computer_wins}  ')
    #     if game.computer_wins and game.user_wins < 3:
    #         game.get_prediction()
    #     else:
    #         print('game end')
    game.get_prediction()

 
play_rps()

2022-08-18 20:31:14.864864: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


2022-08-18 20:31:20.367 Python[67709:5211592] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)


1/1 [==============================] - 2s 2s/step
1. stopped camera
[[6.3209836e-07 9.9446362e-01 5.5352133e-03 4.9912285e-07]]
2. cv_choice var prints: paper
3. You picked: paper. The computer picked paper
It's a draw!


In [11]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()

    seconds = 3 #set how many seconds to run the camera 
    computer_wins = 0
    user_wins = 0
    rounds = 0

    def __init__(self,rounds):
        self.rounds = 0 

    def get_prediction(self, rounds):        
        
        
        while self.rounds < 3:
            # model = load_model('keras_model.h5')
            # cap = cv2.VideoCapture(0)
            # data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            # ret, frame = cap.read()
            # resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            # image_np = np.array(resized_frame)
            # normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            # data[0] = normalized_image
            # cv2.imshow('frame', frame)
            # prediction = model.predict(data)
            # print(prediction) #test to see if the values are changing - REMOVE


            prediction = 'paper'#just a test
            print('get prediction while loop running') #just a test
            self.rounds = self.rounds + 1


            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                print(self.rounds)
                break

            self.stop_camera()#call the method to stop the camera
            self.get_user_choice(prediction)#call the convert the array to a choice
        
        else: 
            print('hit the last else') 
                

        
    def stop_camera(self):
        print('1. stopped camera') #just a test - REMOVE 
        # cap.release()# After the loop release the cap object
        # cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        # np.array(prediction) #convert to array
        # idx_max = prediction.argmax() #find the max value
        # choices = ["rock", "paper", "scissors", "nothing"]
        # user_camera_choice = choices[idx_max]
        user_camera_choice = 'paper2'
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            CvRps.computer_wins += 1
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
            CvRps.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
            CvRps.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
            CvRps.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps(3)
    game.get_prediction(3)


play_rps()

get prediction while loop running
1. stopped camera
paper
2. cv_choice var prints: paper2
3. You picked: paper2. The computer picked paper
No Result: Seems to be an error somewhere
get prediction while loop running
1. stopped camera
paper
2. cv_choice var prints: paper2
3. You picked: paper2. The computer picked scissors
No Result: Seems to be an error somewhere
get prediction while loop running
1. stopped camera
paper
2. cv_choice var prints: paper2
3. You picked: paper2. The computer picked scissors
No Result: Seems to be an error somewhere
hit the last else


In [16]:
import random #for computer choice
import cv2 #to leverage camera
from keras.models import load_model #to run the  model
import numpy as np #for arrays for interpretting the image
import time



class CvRps:

    choice_list = ['rock', 'paper', 'scissors'] #declared this outside the init without self
    start_time = time.time()

    seconds = 3 #set how many seconds to run the camera 
    computer_wins = 0
    user_wins = 0

    def __init__(self,rounds):
        self.rounds = 0 

    def get_prediction(self, rounds):        
        
        
        while self.rounds <= 3:
            model = load_model('keras_model.h5')
            cap = cv2.VideoCapture(0)
            data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
            ret, frame = cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            data[0] = normalized_image
            cv2.imshow('frame', frame)
            prediction = model.predict(data)
            print(prediction) #test to see if the values are changing - REMOVE
    
            self.rounds = self.rounds + 1

            current_time = time.time()
            elapsed_time = current_time - CvRps.start_time
            if elapsed_time > CvRps.seconds:
                if self.rounds <= 3:
                    print('passing')
                    pass 
                else: 
                    break

            self.stop_camera(cap)#call the method to stop the camera
            self.get_user_choice(prediction)#call the convert the array to a choice
        
        else: 
            print('hit the last else') 
                

        
    def stop_camera(self, cap):
        print('1. stopped camera') #just a test - REMOVE 
        cap.release()# After the loop release the cap object
        cv2.destroyAllWindows()# Destroy all the windows
        pass   

    def get_user_choice(self, prediction):
        print(prediction)
        np.array(prediction) #convert to array
        idx_max = prediction.argmax() #find the max value
        choices = ["rock", "paper", "scissors", "nothing"]
        user_camera_choice = choices[idx_max]
        print(f'2. cv_choice var prints: {user_camera_choice}') ##just a test - REMOVE
        self.get_computer_choice(user_camera_choice) 

    def get_computer_choice(self,user_choice):
        computer_choice = random.choice(CvRps.choice_list)
        print(f"3. You picked: {user_choice}. The computer picked {computer_choice}") #just testing to see if it makes it here
        self.get_winner(user_choice, computer_choice)

    def get_winner(self, user_choice, computer_choice):
        if computer_choice == user_choice:
            print("It's a draw!")
        elif computer_choice == 'rock' and user_choice == 'scissors':
            CvRps.computer_wins += 1
            print('You lost')
        elif computer_choice == 'rock' and user_choice == 'paper':
            print('You Won')
            CvRps.user_wins += 1
        elif computer_choice == 'paper' and user_choice == 'rock':
            print('You lost')
            CvRps.computer_wins += 1
        elif computer_choice == 'paper' and user_choice == 'scissors':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'rock':
            print('You won')
            CvRps.user_wins += 1
        elif computer_choice == 'scissors' and user_choice == 'paper':
            print('You lost')
            CvRps.computer_wins += 1
        else:
            print('No Result: Seems to be an error somewhere')

def play_rps():
    game = CvRps(3)
    game.get_prediction(3)
    print('game end')
    cv2.VideoCapture(0).release()# After the loop release the cap object
    cv2.destroyAllWindows()# Destroy all the windows


play_rps()

1/1 [==============================] - 1s 1s/step
[[9.9996674e-01 3.1360076e-05 7.0703003e-08 1.7979771e-06]]
passing
1. stopped camera
[[9.9996674e-01 3.1360076e-05 7.0703003e-08 1.7979771e-06]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 1s/step
[[9.9944836e-01 5.5166020e-04 1.7203015e-10 2.7640686e-08]]
passing
1. stopped camera
[[9.9944836e-01 5.5166020e-04 1.7203015e-10 2.7640686e-08]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 1s/step
[[9.9997950e-01 1.9902533e-05 4.1473690e-08 6.3193073e-07]]
passing
1. stopped camera
[[9.9997950e-01 1.9902533e-05 4.1473690e-08 6.3193073e-07]]
2. cv_choice var prints: rock
3. You picked: rock. The computer picked rock
It's a draw!
1/1 [==============================] - 1s 917ms/step
[[9.9998534e-01 1.4193496e-05 1.5602939e-08 4.8147530e-07]]
game end
